site_name: David Jaggi
site_url: https://davidjaggi.com/
repo_name: "GitHub"
site_author: "David Jaggi"

nav:
  - Home: index.md
  - Blog: blog.md
  - About: about.md

theme:
    name: 'material'
    language: en
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

copyright: Copyright &copy; 2021 David Jaggi

plugins:
  - search
  - blogging:
      dirs:
       - blog
  - roamlinks 